version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: flask run --host 0.0.0.0 --port 80
    ports:
      - 80:80
    volumes:
      - ./src:/app/src
    env_file:
      - .env